// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYydA4soomalePat9Txs6XNeAPtoVrlJg',
    appId: '1:842751620236:web:7766fd8ec2248b4c5337a9',
    messagingSenderId: '842751620236',
    projectId: 'bump-82d8f',
    authDomain: 'bump-82d8f.firebaseapp.com',
    databaseURL: 'https://bump-82d8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bump-82d8f.appspot.com',
    measurementId: 'G-G65N4JN685',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq41gsdpbE2U7Wtaw_TCmOoIoWsSGmZSM',
    appId: '1:842751620236:android:a498e11e2d4da5465337a9',
    messagingSenderId: '842751620236',
    projectId: 'bump-82d8f',
    databaseURL: 'https://bump-82d8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bump-82d8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2uT_zx-p0zm5ND7H0NN0LQKWnisF-l_w',
    appId: '1:842751620236:ios:9fcb6e9fd83166105337a9',
    messagingSenderId: '842751620236',
    projectId: 'bump-82d8f',
    databaseURL: 'https://bump-82d8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bump-82d8f.appspot.com',
    iosClientId: '842751620236-sqc5p80805tk59klteu7v9pt3uc7dsfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2uT_zx-p0zm5ND7H0NN0LQKWnisF-l_w',
    appId: '1:842751620236:ios:9fcb6e9fd83166105337a9',
    messagingSenderId: '842751620236',
    projectId: 'bump-82d8f',
    databaseURL: 'https://bump-82d8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bump-82d8f.appspot.com',
    iosClientId: '842751620236-sqc5p80805tk59klteu7v9pt3uc7dsfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
